### ISSUE TITLE
Result set concurrency incorrectly passed as result set holdability

### ISSUE THREAD

**Issue by mixja** [opendistro-for-elasticsearch/sql-jdbc#63]
When attempting to get Apache Spark to work with this JDBC driver, I came across an issue where the following exception is raised in the driver:

```
java.sql.SQLNonTransientException: Only HOLD_CURSORS_OVER_COMMIT holdability is supported.
        at com.amazon.opendistroforelasticsearch.jdbc.ConnectionImpl.validateResultSetHoldability(ConnectionImpl.java:275)
        at com.amazon.opendistroforelasticsearch.jdbc.ConnectionImpl.validateResultSetCharacteristics(ConnectionImpl.java:260)
        at com.amazon.opendistroforelasticsearch.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:282)
        at org.apache.spark.sql.execution.datasources.jdbc.JDBCRDD.compute(JDBCRDD.scala:300)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
        at org.apache.spark.scheduler.Task.run(Task.scala:121)
        at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

In this line:

https://github.com/opendistro-for-elasticsearch/sql-jdbc/blob/625614647c5110daa4e524143d55ecabb8e50794/src/main/java/com/amazon/opendistroforelasticsearch/jdbc/ConnectionImpl.java#L282

it appears that `resultSetConcurrency` is supplied twice to the `validateResultSetCharacteristics` method call, when it should follow the approach of this:

https://github.com/opendistro-for-elasticsearch/sql-jdbc/blob/625614647c5110daa4e524143d55ecabb8e50794/src/main/java/com/amazon/opendistroforelasticsearch/jdbc/ConnectionImpl.java#L250

I forked the repo and built my own driver with the following fix and it resolved the issue:

https://github.com/mixja/sql-jdbc/commit/8ac4cc9d434a357c962d115183d0753646c2a923

**Comment by anirudha** [comment]
Could you please send a pull request thank you. we would happily take a look and merge. Any test you will help a lot.
