### ISSUE TITLE
JDBC TEST 400

### ISSUE THREAD

**Issue by EveyWu** [opendistro-for-elasticsearch/sql-jdbc#70]
```
    @Test
    public void queryTest() throws SQLException {
        String url = "jdbc:elasticsearch://node01:9200";
        Properties properties = new Properties();
        //properties.put("user", "test_admin");
        //properties.put("password", "x-pack-test-password");

        Connection connection = DriverManager.getConnection(url, properties);

        try (Statement statement = connection.createStatement()) {
            ResultSet results = statement.executeQuery("SELECT name, page_count FROM library");
        }
    }
```

response:
```
java.sql.SQLException: Error executing query

	at com.amazon.opendistroforelasticsearch.jdbc.StatementImpl.executeQueryRequest(StatementImpl.java:84)
	at com.amazon.opendistroforelasticsearch.jdbc.StatementImpl.executeQueryX(StatementImpl.java:61)
	at com.amazon.opendistroforelasticsearch.jdbc.StatementImpl.executeQuery(StatementImpl.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: com.amazon.opendistroforelasticsearch.jdbc.protocol.http.HttpException: HTTP Code: 400. Message: Bad Request. Raw response received: {"error":{"root_cause":[{"type":"invalid_index_name_exception","reason":"Invalid index name [_opendistro], must not start with '_', '-', or '+'","index_uuid":"_na_","index":"_opendistro"}],"type":"invalid_index_name_exception","reason":"Invalid index name [_opendistro], must not start with '_', '-', or '+'","index_uuid":"_na_","index":"_opendistro"},"status":400}
	at com.amazon.opendistroforelasticsearch.jdbc.protocol.http.JsonHttpResponseHandler.checkResponseForErrors(JsonHttpResponseHandler.java:83)
	at com.amazon.opendistroforelasticsearch.jdbc.protocol.http.JsonHttpResponseHandler.handleResponse(JsonHttpResponseHandler.java:52)
	at com.amazon.opendistroforelasticsearch.jdbc.protocol.http.JsonHttpResponseHandler.handleResponse(JsonHttpResponseHandler.java:45)
	at com.amazon.opendistroforelasticsearch.jdbc.protocol.http.JsonHttpProtocol.execute(JsonHttpProtocol.java:88)
	at com.amazon.opendistroforelasticsearch.jdbc.StatementImpl.executeQueryRequest(StatementImpl.java:72)
	... 25 more
```

![image](https://user-images.githubusercontent.com/59307607/77606210-d7191200-6f51-11ea-85fc-d5fd29d32252.png)

**Comment by EveyWu** [comment]
ES 7.5.1

HttpResponseProxy{HTTP/1.1 400 Bad Request [Warning: 299 Elasticsearch-7.5.1-3ae9ac9a93c95bd0cdc054951cf95d88e1e18d96 "[types removal] Specifying types in document index requests is deprecated, use the typeless endpoints instead (/{index}/_doc/{id}, /{index}/_doc, or /{index}/_create/{id}).", content-type: application/json; charset=UTF-8, content-length: 365] ResponseEntityProxy{[Content-Type: application/json; charset=UTF-8,Content-Length: 365,Chunked: false]}}

**Comment by EveyWu** [comment]
have to install plugin of [sql](https://github.com/opendistro-for-elasticsearch/sql)
